In [1]:
%reload_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
from fastai.imports import *
from fastai.transforms import *
from fastai.conv_learner import *
from fastai.model import *
from fastai.dataset import *
from fastai.sgdr import *
from fastai.plots import *

In [3]:
PATH = "data/dogbreed/"

In [4]:
sz = 256
arch = inceptionresnet_2
bs = 32
# Jeremy tried 224, 58 and 299, 58

In [5]:
label_csv = f'{PATH}labels.csv'
n = len(list(open(label_csv))) - 1
val_idxs = get_cv_idxs(n)

In [6]:
label_df = pd.read_csv(label_csv)

In [7]:
def get_data(sz, bs):
    tfms = tfms_from_model(arch, sz, aug_tfms=transforms_side_on, max_zoom=1.1)
    data = ImageClassifierData.from_csv(PATH, 'train', f'{PATH}labels.csv', test_name='test',
                                        val_idxs=val_idxs, suffix='.jpg', tfms=tfms, bs=bs)
    return data if sz>300 else data.resize(340, 'tmp')

## Precompute

In [8]:
data = get_data(sz, bs)

A Jupyter Widget

In [9]:
learn = ConvLearner.pretrained(arch, data, precompute=True)

In [10]:
learn.fit(1e-2, 2)

A Jupyter Widget

[ 0.       0.53306  0.3378   0.90604]                        
[ 1.       0.38422  0.32213  0.90172]                        



In [11]:
learn.fit(1e-2, 3)

A Jupyter Widget

[ 0.       0.30422  0.34763  0.90123]                        
[ 1.       0.29334  0.33403  0.90806]                        
[ 2.       0.27051  0.34761  0.90165]                        



## Augment

In [12]:
from sklearn import metrics

In [13]:
data = get_data(sz, bs)

A Jupyter Widget

In [14]:
learn = ConvLearner.pretrained(arch, data, precompute=True, ps=0.5)

In [15]:
learn.fit(1e-2, 2)

A Jupyter Widget

[ 0.       0.54317  0.34478  0.90367]                        
[ 1.       0.40056  0.32847  0.90611]                        



In [16]:
learn.precompute=False
learn.bn_freeze=True

In [17]:
learn.fit(1e-2, 5, cycle_len=1)

A Jupyter Widget

[ 0.       0.39629  0.30747  0.91343]                        
[ 1.       0.42454  0.30023  0.91839]                        
[ 2.       0.38731  0.31     0.91148]                        
[ 3.       0.38091  0.29987  0.91734]                        
[ 4.       0.34538  0.30767  0.9135 ]                        



In [18]:
learn.save('224_ir2_pre')

In [19]:
learn.load('224_ir2_pre')

## Increase size

In [20]:
learn.set_data(get_data(350, bs))
learn.freeze()

In [21]:
learn.fit(1e-2, 3, cycle_len=1)

A Jupyter Widget

[ 0.       0.27647  0.20591  0.93799]                        
[ 1.       0.25698  0.19986  0.93897]                        
[ 2.       0.26734  0.20072  0.94043]                        



In [22]:
learn.fit(1e-2, 3, cycle_len=1, cycle_mult=2)

A Jupyter Widget

[ 0.       0.24205  0.20619  0.93945]                        
[ 1.       0.25491  0.21365  0.94092]                        
[ 2.       0.24179  0.20915  0.93994]                        
[ 3.       0.22803  0.21071  0.94629]                        
[ 4.       0.22583  0.20927  0.94141]                        
[ 5.       0.20221  0.20807  0.93799]                        
[ 6.       0.21046  0.20538  0.94043]                        



In [23]:
learn.save('350_ir2_pre')

In [24]:
learn.load('350_ir2_pre')

In [27]:
learn.fit(1e-2, 1, cycle_len=2)

A Jupyter Widget

[ 0.       0.22223  0.21328  0.93603]                        
[ 1.       0.18307  0.20662  0.93799]                        



In [28]:
learn.save('350_ir2_pre')

In [29]:
learn.load('350_ir2_pre')

In [30]:
learn.set_data(get_data(400, bs))
learn.freeze()

In [31]:
learn.fit(1e-2, 3, cycle_len=1)

A Jupyter Widget

[ 0.       0.20083  0.21646  0.93897]                        
[ 1.       0.23899  0.21905  0.94043]                        
[ 2.       0.21742  0.21547  0.93799]                        



In [32]:
learn.fit(1e-2, 3, cycle_len=1, cycle_mult=2)

A Jupyter Widget

[ 0.       0.2118   0.2139   0.93799]                        
[ 1.       0.207    0.22073  0.93848]                        
[ 2.       0.18115  0.21951  0.93897]                        
[ 3.       0.20123  0.21724  0.93897]                        
[ 4.       0.19847  0.2199   0.93408]                        
[ 5.       0.17067  0.2186   0.93555]                        
[ 6.       0.17673  0.22168  0.9331 ]                        



In [33]:
learn.save('400_ir2_pre')

In [34]:
learn.load('400_ir2_pre')

In [35]:
learn.fit(1e-2, 1, cycle_len=2)

A Jupyter Widget

[ 0.       0.20529  0.22238  0.93701]                        
[ 1.       0.16967  0.22149  0.93603]                        



In [36]:
learn.save('400_ir2_pre')

In [37]:
learn.load('400_ir2_pre')

In [38]:
log_preds, y = learn.TTA()
probs_pre = np.exp(log_preds)
accuracy(log_preds, y), metrics.log_loss(y, probs_pre)

 25%|██▌       | 1/4 [01:35<04:46, 95.62s/it]

KeyboardInterrupt: 

In [ ]:
log_preds, y = learn.TTA(is_test=True)
probs_ir2_400 = np.exp(log_preds)

In [ ]:
def save_array(fname, arr): c=bcolz.carray(arr, rootdir=fname, mode='w'); c.flush()

In [ ]:
save_array('probs_ir2_400.bc', probs_ir2_400)

In [ ]:
learn.save('400_ir2_pre')

## Use whole dataset now

In [31]:
learn.load('299_pre')

In [32]:
def get_data_whole(sz, bs):
    tfms = tfms_from_model(arch, sz, aug_tfms=transforms_side_on, max_zoom=1.1)
    data = ImageClassifierData.from_csv(PATH, 'train', f'{PATH}labels.csv', test_name='test',
                                        val_idxs=[0], suffix='.jpg', tfms=tfms, bs=bs)
    return data if sz>300 else data.resize(340, 'tmp')

In [33]:
def load_array(fname): return bcolz.open(fname)[:]

In [34]:
data = get_data_whole(sz, bs)

A Jupyter Widget

In [35]:
learn = ConvLearner.pretrained(arch, data, precompute=True)
learn.freeze()

100%|██████████| 1/1 [00:00<00:00,  2.82it/s]


In [36]:
learn.fit(1e-2, 5)

A Jupyter Widget

[ 0.       0.75786  0.01884  1.     ]                         
[ 1.       0.38308  0.00202  1.     ]                         
[ 2.       0.27529  0.00073  1.     ]                         
[ 3.       0.22052  0.00052  1.     ]                         
[ 4.       0.19112  0.00022  1.     ]                         



In [37]:
learn = ConvLearner.pretrained(arch, data, precompute=True, ps=0.5)

In [38]:
learn.fit(1e-2, 2)

A Jupyter Widget

[ 0.       0.94042  0.00524  1.     ]                         
[ 1.       0.48962  0.00265  1.     ]                         



In [39]:
learn.precompute = False
learn.bn_freeze = True

In [ ]:
learn.fit(1e-2, 3, cycle_len=1, cycle_mult=2)

A Jupyter Widget

[ 0.       0.44712  0.00127  1.     ]                        
[ 1.       0.39743  0.00121  1.     ]                        
[ 2.       0.34848  0.00075  1.     ]                        
[ 3.       0.35622  0.00137  1.     ]                        
[ 4.       0.31755  0.00057  1.     ]                        
[ 5.       0.28701  0.00074  1.     ]                        
 76%|███████▌  | 134/177 [03:41<01:10,  1.65s/it, loss=0.29] 

In [ ]:
learn.set_data(get_data_whole(299, bs))
learn.freeze()

In [ ]:
learn.fit(1e-2, 3, cycle_len=1, cycle_mult=2)

In [ ]:
log_preds, y = learn.TTA(is_test=True)
probs_resnx101_64_full = np.exp(log_preds)
#accuracy(log_preds, y), metrics.log_loss(y, probs)

In [ ]:
save_array('probs_resnx101_64_full.bc', probs_resnx101_64_full)

In [ ]:
learn.save('299_full')

## Try ensembling
### Use another arch first

## Save to file for submission

In [33]:
df = pd.DataFrame(probs_ir2)
df.columns = data.classes
df.insert(0, 'id', [o[5:-4] for o in data.test_ds.fnames])

In [34]:
df.head()

id  affenpinscher  afghan_hound  \
0  fd1a7be32f10493735555e62913c0841   2.101389e-06  7.957380e-07   
1  5273d42f02b4715cb93845205995ef64   1.615717e-05  1.668898e-05   
2  442057a3142f4d75a1023db363e2fb54   7.130004e-07  8.126507e-07   
3  fb03302b030afd122e0f4936c158f6c1   6.470754e-05  5.273749e-06   
4  511ca6e3539192aa5c8747bb697e0525   8.379841e-07  1.200375e-06   

   african_hunting_dog      airedale  american_staffordshire_terrier  \
0         9.901231e-07  7.696650e-07                    4.725467e-07   
1         2.292900e-06  3.470073e-06                    1.326146e-06   
2         2.995882e-07  1.080347e-06                    3.360327e-07   
3         7.179740e-07  6.052573e-06                    2.462417e-05   
4         5.936035e-07  7.524296e-07                    2.809074e-06   

    appenzeller  australian_terrier       basenji        basset  \
0  3.137218e-07        1.815584e-07  1.709327e-07  4.579634e-07   
1  9.195463e-07        6.441616e-08  8.183958e-07  1.369859e-06   
2  8.103186e-06        6.558137e-08  9.681415e-08  7.517328e-06   
3  4.126265e-06        2.563426e-05  1.258198e-05  2.768924e-05   
4  4.269319e-07        1.336144e-05  2.859274e-07  1.571820e-06   

         ...            toy_poodle   toy_terrier        vizsla  walker_hound  \
0        ...          2.395443e-06  2.345402e-06  8.872038e-07  2.088811e-06   
1        ...          2.356505e-06  5.158620e-07  1.096716e-06  6.168519e-06   
2        ...          2.840640e-07  7.324162e-07  4.261292e-06  5.974223e-05   
3        ...          7.947544e-05  1.446267e-05  7.264930e-06  1.506572e-05   
4        ...          4.072642e-06  9.853200e-07  2.454565e-07  2.628426e-07   

     weimaraner  welsh_springer_spaniel  west_highland_white_terrier  \
0  6.659964e-08            3.753928e-07                 3.749388e-07   
1  5.028619e-06            3.254074e-06                 1.100742e-06   
2  9.524963e-07            1.255658e-07                 1.527046e-06   
3  1.073374e-05            2.775627e-06                 9.247089e-06   
4  1.317447e-06            4.162125e-07                 2.284507e-05   

        whippet  wire-haired_fox_terrier  yorkshire_terrier  
0  1.273274e-06             4.798866e-07       3.512119e-08  
1  2.905195e-06             8.317512e-06       5.890093e-07  
2  1.828355e-07             7.973781e-07       5.305102e-07  
3  2.588709e-06             6.563337e-06       2.558486e-04  
4  4.138440e-07             1.315784e-05       9.399819e-07  

[5 rows x 121 columns]

In [35]:
SUBM = f'{PATH}results_2/'
os.makedirs(SUBM, exist_ok=True)
df.to_csv(f'{SUBM}submission11.csv', index=False)
#df.to_csv(f'{SUBM}subm.gz', compression='gzip', index=False)

## Individual prediction

In [ ]:
fn = data.val_ds.fnames[0]

In [ ]:
fn

In [ ]:
Image.open(PATH+fn).resize((150, 150))

In [ ]:
trn_tfms, val_tfms = tfms_from_model(arch, sz)

In [ ]:
ds = FilesIndexArrayDataset([fn], np.array([0]), val_tfms, PATH)
dl = DataLoader(ds)
preds = learn.predict_dl(dl)
np.argmax(preds)

In [ ]:
im = trn_tfms(Image.open(PATH+fn))
preds = to_np(learn.model(V(T(im[None]).cude())))
np.argmax(preds)

In [ ]:
trn_tfms, val_tfms = tfms_from_model(arch, sz)

In [ ]:
im = trn_tfms(Image.open(PATH+fn))
preds = learn.predict_array(im[None])
np.argmax(preds)

## Confusion matrix

In [ ]:
preds = np.argmax(log_preds, axis=1)
probs = np.exp(log_preds[:,1])

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y, preds)

In [ ]:
plot_confusion_matrix(cm, data.classes)