In [1]:
%reload_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
from fastai.imports import *
from fastai.transforms import *
from fastai.conv_learner import *
from fastai.model import *
from fastai.dataset import *
from fastai.sgdr import *
from fastai.plots import *

In [3]:
PATH = "data/dogscats/"

In [4]:
sz = 224
arch = resnet50
bs = 64

In [5]:
tfms = tfms_from_model(arch, sz, aug_tfms=transforms_side_on, max_zoom=1.1)
data = ImageClassifierData.from_paths(PATH, tfms=tfms, bs=bs)
learn = ConvLearner.pretrained(arch, data)
%time learn.fit(1e-2, 3, cycle_len=1)

A Jupyter Widget

[ 0.       0.04379  0.02641  0.99219]                         
[ 1.       0.03055  0.02677  0.99121]                         
[ 2.       0.03905  0.02688  0.99072]                         

CPU times: user 7min 24s, sys: 1min 28s, total: 8min 52s
Wall time: 9min 49s


In [6]:
learn.unfreeze()
learn.bn_freeze(True)
%time learn.fit([1e-5, 1e-4, 1e-2], 1, cycle_len=1)

A Jupyter Widget

[ 0.       0.02151  0.02666  0.99121]                         

CPU times: user 7min 54s, sys: 53.1 s, total: 8min 47s
Wall time: 9min 1s


In [7]:
%time log_preds, y = learn.TTA()
metrics.log_loss(y, np.exp(log_preds)), accuracy(log_preds, y)

CPU times: user 37.6 s, sys: 10.8 s, total: 48.4 s
Wall time: 1min 42s


(0.017944269749224282, 0.99350000000000005)